const logos = {
  adobeCreativeCloud: require('./logos/adobe creative cloud.png'),
  androidStudio: require('./logos/android studio.png'),
  apollo: require('./logos/apollo.png'),
  apolloServer: require('./logos/apollo-server.png'),
  asana: require('./logos/asana.png'),
  audition: require('./logos/audition.png'),
  aws: require('./logos/aws.png'),
  bitbucket: require('./logos/bitbucket.png'),
  bootstrap: require('./logos/bootstrap.png'),
  digitalOcean: require('./logos/digital-ocean.png'),
  django: require('./logos/django with python.png'),
  docker: require('./logos/docker.png'),
  electron: require('./logos/electron.png'),
  excel: require('./logos/excel.png'),
  express: require('./logos/express.png'),
  finalCutPro: require('./logos/final cut pro.png'),
  firebase: require('./logos/firebase.png'),
  flaticon: require('./logos/flaticon.png'),
  formik: require('./logos/formik.png'),
  freepik: require('./logos/freepik.png'),
  gatsby: require('./logos/gatsby.png'),
  git: require('./logos/git.png'),
  github: require('./logos/github.png'),
  graphene: require('./logos/graphene.png'),
  graphql: require('./logos/graphql.png'),
  guitarPro: require('./logos/guitar pro.png'),
  heroku: require('./logos/heroku.png'),
  HTMLandCSS: require('./logos/HTML5 CSS3.png'),
  html5up: require('./logos/html5up.png'),
  i18next: require('./logos/i18next.png'),
  illustrator: require('./logos/illustrator.png'),
  java: require('./logos/java.png'),
  javascript: require('./logos/javascript.png'),
  jira: require('./logos/jira.png'),
  jupyter: require('./logos/jupyter.png'),
  lodash: require('./logos/lodash.png'),
  logicPro: require('./logos/logic pro.png'),
  masonic: require('./logos/masonic.png'),
  materialUI: require('./logos/materialUI.png'),
  mathematica: require('./logos/mathematica.png'),
  mockaroo: require('./logos/mockaroo.png'),
  mongodb: require('./logos/mongodb.png'),
  mongoose: require('./logos/mongoose.png'),
  musescore: require('./logos/musescore.png'),
  nestjs: require('./logos/nestjs.png'),
  node: require('./logos/node.png'),
  pgadmin: require('./logos/pgadmin.png'),
  photoshop: require('./logos/photoshop.png'),
  postgres: require('./logos/postgres.png'),
  postman: require('./logos/postman.png'),
  powerpoint: require('./logos/powerpoint.png'),
  python: require('./logos/python.png'),
  react: require('./logos/react.png'),
  reactAwesomeReveal: require('./logos/react-awesome-reveal.png'),
  reactNative: require('./logos/react native.png'),
  redis: require('./logos/redis.png'),
  redux: require('./logos/redux.png'),
  reduxForm: require('./logos/redux-form.png'),
  reduxSaga: require('./logos/redux-saga.png'),
  sapper: require('./logos/sapper.png'),
  sketch: require('./logos/sketch.png'),
  sqlite3: require('./logos/sqlite3.png'),
  svelte: require('./logos/svelte.png'),
  swift: require('./logos/swift.png'),
  typeGraphQL: require('./logos/type-graphql.png'),
  typeORM: require('./logos/typeORM.png'),
  typescript: require('./logos/typescript.png'),
  wolframLanguage: require('./logos/wolfram language.png'),
  word: require('./logos/word.png'),
  wordpress: require('./logos/wordpress.png'),
  xcode: require('./logos/xcode.png'),
};

export default logos;
